### ISSUE TITLE
InstallJRE.ps1

### ISSUE THREAD

**Issue by eseyman** [juangranados/powershell-scripts#1]
[this isn't really an issue, sorry]

I've been handed a InstallJRE powerscript file that lists you as author. Is there a canonical version of this script somewhere? I would like to ensure I'm using the latest version.

**Comment by juangranados** [comment]
Hi @eseyman! I forgot to upload Install-JRE.ps1 after Microsoft closed Script Center.

I updated Download-JRE.ps1 because Oracle is using Javascript to hide download links. 

Install-JRE.ps1 is still working in my environment.

I uploaded both scripts to [Install JRE](https://github.com/juangranados/powershell-scripts/blob/main/Install%20JRE)

Regards!
